---
# This playbook configures an already installed UF (uf-install.yml) to:
#  1) Connect to the deployment server.
#  2) Forward _internal logs to the indexer tier.

- name: Apply prereqs to all nodes
  hosts: "{{ splunk_uf_hosts | default('ufhosts') }}"
  gather_facts: false
  roles:
    - prereqs

- name: Configure Splunk Universal Forwarder
  hosts: "{{ splunk_uf_hosts | default('ufhosts') }}"
  roles:
    - uf-config
