---
# This playbook upgrades the Splunk Universal Forwarder

- name: Apply prereqs to all nodes
  hosts: "{{ splunk_uf_hosts | default('ufhosts') }}"
  gather_facts: false
  roles:
    - prereqs

- name: Upgrade Splunk Universal Forwarder
  hosts: "{{ splunk_uf_hosts | default('ufhosts') }}"
  roles:
    - uf-upgrade
