---

- name: Back up the Splunk configuration in {{ splunk_home }}/etc
  ansible.builtin.include_role:
    name: splunk-common
    tasks_from: archive
  vars:
    backup_source: "{{ splunk_home }}/etc"
    backup_label: etc
