---

- name: Install python3 or python-minimal if not already available (ansible prereq)
  raw: bash -c "test -e /usr/bin/python3 || test -e /usr/bin/python || (apt -qqy update && apt install -qy python3) || (apt -qqy update && apt install -qy python-minimal) || (yum -y install python3) || (dnf -y install python3)"
  become: yes
  ignore_errors: yes
